# Generated by Django 3.1.6 on 2021-02-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210227_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
