# Generated by Django 3.1.6 on 2021-03-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210309_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='shop.Category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(max_length=100, verbose_name='Тип напитка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(max_length=900, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(help_text='введите название блюда', max_length=100, verbose_name='Название блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company', verbose_name='компания'),
        ),
    ]
